spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq:
  queue:
    name: demo_queue
    json:
      name: demo_json_queue
  exchange:
    name: demo_exchange
  routing:
    key: demo_routing
    json:
      key: demo_json_routing
